---
- name: install apache
  hosts: webservers
  remote_user: ansible
  become: true
  vars_files: defaults.yml

  tasks:
    - name: Install apache
      yum:
        name: httpd
        update_cache: yes
        state: latest
    - name:
      systemd:
        name: httpd
        state: started
        enabled: yes
